config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :task_projects
  resources :template_projects do
    collection do
      post 'import'
      get 'export'
    end
  end

  root 'task_projects#index'
  namespace :api do
    resources :tasks, only: [:index, :create, :update, :destroy] do
      member do
        put 'position'
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks

  validates :title, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  TASK_TYPE = ['feature', 'release']
  STATUS_TYPE = ['unstarted', 'started', 'finished']

  acts_as_list scope: :project
  belongs_to :project

  validates :uuid, presence: true, uniqueness: true, length: {is: 36}
  validates :task_type , inclusion: {in: TASK_TYPE}
  validates :status, inclusion: {in: STATUS_TYPE}
  validates :point, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 3}
  validates :title, presence: true
end

app/models/task_project.rb
class TaskProject < Project
end

app/models/template_project.rb
class TemplateProject < Project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < Api::ApplicationController
  before_action :set_project
  before_action :set_task, only: [:update, :destroy, :position]

  def index
    @tasks = @project.tasks.order(position: :asc)
  end

  def create
    @task = @project.tasks.new task_params
    if @task.save
      head :ok
    else
      render 'error', formats: [:json], handlers: [:jbuilder], status: :bad_request
    end
  end

  def update
    if @task.update task_params
      head :ok
    else
      render 'error', formats: [:json], handlers: [:jbuilder], status: :bad_request
    end
  end

  def destroy
    @task.destroy
    head :ok
  end

  def position
    @task.insert_at params[:position].to_i
    head :ok
  end

  private

  def set_project
    @project = current_user.projects.where(id: params[:project_id]).first
    head :not_found unless @project
  end

  def set_task
    @task = @project.tasks.where(uuid: params[:id]).first
    head :not_found unless @task
  end

  def task_params
    params.require(:task).permit :uuid, :task_type, :status, :point, :title, :description, :position, :started_at, :finished_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/task_projects_controller.rb
class TaskProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task_project, only: [:edit, :update, :destroy, :show]
  before_action :set_template_projects, only: [:new, :create]
  respond_to :html

  def index
    @task_projects = TaskProject.where(user: current_user).order(created_at: :desc).page params[:page]
  end

  def new
    @task_project = TaskProject.new user: current_user
  end

  def create
    if params[:template_project_id].present?
      @template_project = TemplateProject.find params[:template_project_id]
      @task_project = TaskProjectDuplicator.execute @template_project, params
    else
      @task_project = TaskProject.new task_project_params
    end
    @task_project.user = current_user
    flash[:success] = 'saved' if @task_project.save
    respond_with @task_project, location: task_projects_path
  end

  def edit
  end

  def update
    flash[:success] = 'saved' if @task_project.update task_project_params
    respond_with @task_project, location: task_projects_path
  end

  def destroy
    @task_project.destroy
    redirect_to task_projects_path
  end

  def show
  end

  private

  def set_task_project
    @task_project = TaskProject.where(user: current_user, id: params[:id]).first
  end

  def set_template_projects
    @template_projects = TemplateProject.where user: current_user
  end

  def task_project_params
    params.require(:task_project).permit :title
  end
end

app/controllers/template_projects_controller.rb
class TemplateProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_template_project, only: [:edit, :update, :destroy, :show]
  before_action :set_template_projects, only: [:export]
  respond_to :html

  def index
    @template_projects = TemplateProject.where(user: current_user).order(created_at: :desc).page params[:page]
  end

  def new
    @template_project = TemplateProject.new user: current_user
  end

  def create
    @template_project = TemplateProject.new template_project_params
    @template_project.user = current_user
    flash[:success] = 'saved' if @template_project.save
    respond_with @template_project, location: template_projects_path
  end

  def edit
  end

  def update
    flash[:success] = 'saved' if @template_project.update template_project_params
    respond_with @template_project, location: template_projects_path
  end

  def destroy
    @template_project.destroy
    redirect_to template_projects_path
  end

  def show
  end

  def import
    TemplateProjectImporter.execute current_user, params[:file].read
    redirect_to template_projects_path
  end

  def export
    data = render_to_string template: 'template_projects/export.json.jbuilder', locals: { template_projects: @template_projects }
    send_data data, type: 'application/json', filename: 'template.json'
  end

  private

  def set_template_projects
    @template_projects = TemplateProject.all
  end

  def set_template_project
    @template_project = TemplateProject.where(user: current_user, id: params[:id]).first
  end

  def template_project_params
    params.require(:template_project).permit :title
  end
end

app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

app/helpers/api/tasks_helper.rb
module Api::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_projects_helper.rb
module TaskProjectsHelper
end

app/helpers/template_projects_helper.rb
module TemplateProjectsHelper
end

app/views/application/_error.html.haml
- unless errors.empty?
  .alert.alert-danger{role: 'alert'}
    %ul
    - errors.full_messages.each do |message|
      %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TaskManager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
%body
  .navbar.navbar-inverse{role: 'navigation'}
    .container
      .navbar-header
        %button.navbar-toggle{type: 'button', 'data-toggle' => 'collapse',  'data-target' => '.navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        =link_to 'Task Manager', root_path, class: 'navbar-brand'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li{class: yield(:active) == 'task_projects' ? 'active' : ''}= link_to 'project', task_projects_path
          %li{class: yield(:active) == 'template_projects' ? 'active' : ''}= link_to 'template project', template_projects_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to current_user.email, '#'
            %li= link_to 'sign out', destroy_user_session_path, method: :delete

  .container
    = bootswatch_flash
    = yield

app/views/task_projects/_form.html.haml
= form_for @task_project, html: {class: 'form-horizontal', role: 'form'} do |f|
  = render 'error', errors: f.object.errors
  .form-group
    %label.col-sm-2.control-label{for: 'project_title'} title
    .col-sm-10
      = f.text_field :title, class: 'form-control'

  - if f.object.new_record?
    .form-group
      %label.col-sm-2.control-label{for: 'project_template_id'} Template
      .col-sm-10
        = select_tag :template_project_id, options_from_collection_for_select(@template_projects, :id, :title), include_blank: true, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      %button.btn.btn-default{type: 'submit'} save

app/views/task_projects/_task_form.html.haml
%form.form-horizontal{'v-show' => 'isEdit || isNew', ' v-validate' => true}
  %span.glyphicon.glyphicon-trash{'v-show' => 'isEdit', 'v-on' => 'click: destroy(this)'}

  .form-group
    %label.col-sm-2.control-label
      %span Type
      %i.fa.fa-asterisk
    .col-sm-10
      %select.form-control{'v-model' => 'task_type | required'}
        %option feature
        %option release

  .form-group
    %label.col-sm-2.control-label
      %span Point
      %i.fa.fa-asterisk
    .col-sm-10
      %select.form-control{'v-model' => 'point | required | numeric min:0 max:3'}
        %option 0
        %option 1
        %option 2
        %option 3

  .form-group
    %label.col-sm-2.control-label
      %span Status
      %i.fa.fa-asterisk
    .col-sm-10
      %select.form-control{'v-model' => 'status | required'}
        %option unstarted
        %option started
        %option finished

  .form-group
    %label.col-sm-2.control-label
      %span Title
      %i.fa.fa-asterisk
    .col-sm-10
      %input.form-control{type: 'text', 'v-model' => 'title | required'}

  .form-group
    %label.col-sm-2.control-label Description
    .col-sm-10
      %textarea.form-control{rows: 5, 'v-model' => 'description'}

  .form-group
    .col-sm-offset-2.col-sm-10
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: save(this)', 'v-attr' => 'disabled: !$valid'}Save
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: close(this)', 'v-show' => 'isEdit'}Cancel
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: clear()', 'v-show' => 'isNew'}Clear

app/views/task_projects/edit.html.haml
- content_for :active, 'task_projects'

.page-header
  %h1 project

%ol.breadcrumb
  %li= link_to 'project', task_projects_path
  %li.active edit

= render 'form'

app/views/task_projects/index.html.haml
- content_for :active, 'task_projects'

.page-header
  %h1 project

.mb10
  =link_to new_task_project_path, class: 'btn btn-primary' do
    %i.fa.fa-plus

.panel.panel-default
  %table.table
    %thead
    %tr
      %th title
      %th
    %tbody
    - @task_projects.each do |task_project|
      %tr
        %td= link_to task_project.title, task_project_path(task_project)
        %td
          = link_to edit_task_project_path(task_project) do
            %i.fa.fa-lg.fa-edit
          = link_to task_project_path(task_project), method: :delete, data: {confirm: 'are you sure?'} do
            %i.fa.fa-lg.fa-trash

.text-center
  = paginate @task_projects, theme: 'bootstrap'

app/views/task_projects/new.html.haml
- content_for :active, 'task_projects'

.page-header
  %h1 project

%ol.breadcrumb
  %li= link_to 'project', task_projects_path
  %li.active new

= render 'form'

app/views/task_projects/show.html.haml
- content_for :active, 'task_projects'

%ol.breadcrumb
  %li= link_to 'project', task_projects_path
  %li.active= @task_project.title

#task-form
  %button.btn.btn-primary.mb10{'v-on' => 'click: close()'}
    %i.fa.fa-plus
  =render 'task_form'

%ul#task-list.list-group{data: {'project-id' => @task_project.id}}
  %li.list-group-item{'v-class' => "list-group-item-danger: task_type == 'release' && status != 'finished', list-group-item-success: status == 'finished'", 'v-repeat' => 'tasks'}
    %i.fa.fa-lg{'v-class' => 'fa-caret-right: !isEdit, fa-caret-down: isEdit', 'v-on' => 'click: edit(this)'}
    %i.fa.fa-star {{point}}
    %span {{passedTime}}
    %i.fa.fa-comment{'v-show' => "description != ''", 'v-on' => 'mouseenter: popover = true, mouseleave: popover = false'}
      .popover.bottom{'v-class' => 'static-popover: popover'}
        %h3.popover-title {{title}}
        .popover-content{'v-html' => 'description | indent'}
    %span {{title}}
    %button.btn.pull-right.btn-xs.status-button{'v-show' => "status != 'finished'", 'v-class' => "btn-primary: status == 'unstarted', btn-warning: status == 'started'", 'v-on' => 'click: updateStatus(this)'} {{status | status}}
    =render 'task_form'

app/views/template_projects/_form.html.haml
= form_for @template_project, html: {class: 'form-horizontal', role: 'form'} do |f|
  = render 'error', errors: f.object.errors
  .form-group
    %label.col-sm-2.control-label{for: 'project_title'} title
    .col-sm-10
      = f.text_field :title, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      %button.btn.btn-default{type: 'submit'} save

app/views/template_projects/_task_form.html.haml
%form.form-horizontal{'v-show' => 'isEdit || isNew', ' v-validate' => true}
  %span.glyphicon.glyphicon-trash{'v-show' => 'isEdit', 'v-on' => 'click: destroy(this)'}

  .form-group
    %label.col-sm-2.control-label
      %span Type
      %i.fa.fa-asterisk
    .col-sm-10
      %select.form-control{'v-model' => 'task_type | required'}
        %option feature
        %option release

  .form-group
    %label.col-sm-2.control-label
      %span Point
      %i.fa.fa-asterisk
    .col-sm-10
      %select.form-control{'v-model' => 'point | required | numeric min:0 max:3'}
        %option 0
        %option 1
        %option 2
        %option 3

  %input{type: 'hidden', 'v-model' => 'status | required', value: 'unstarted'}

  .form-group
    %label.col-sm-2.control-label
      %span Title
      %i.fa.fa-asterisk
    .col-sm-10
      %input.form-control{type: 'text', 'v-model' => 'title | required'}

  .form-group
    %label.col-sm-2.control-label Description
    .col-sm-10
      %textarea.form-control{rows: 5, 'v-model' => 'description'}

  .form-group
    .col-sm-offset-2.col-sm-10
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: save(this)', 'v-attr' => 'disabled: !$valid'}Save
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: close(this)', 'v-show' => 'isEdit'}Cancel
      %button.btn.btn-default{type: 'button', 'v-on' => 'click: clear()', 'v-show' => 'isNew'}Clear

app/views/template_projects/edit.html.haml
- content_for :active, 'template_projects'

.page-header
  %h1 template project

%ol.breadcrumb
  %li= link_to 'template project', template_projects_path
  %li.active edit

= render 'form'

app/views/template_projects/index.html.haml
- content_for :active, 'template_projects'

.page-header
  %h1 template project

.mb10
  = link_to new_template_project_path, class: 'btn btn-primary' do
    %i.fa.fa-plus
  %span.btn.btn-primary.btn-file
    = form_tag import_template_projects_path, multipart: true, class: 'fa fa-upload', id: 'js-upload-form' do
      = file_field_tag :file
  = link_to export_template_projects_path, class: 'btn btn-primary' do
    %i.fa.fa-download

.panel.panel-default
  %table.table
    %thead
    %tr
      %th title
      %th
    %tbody
    - @template_projects.each do |template_project|
      %tr
        %td= link_to template_project.title, template_project_path(template_project)
        %td
          = link_to edit_template_project_path(template_project) do
            %i.fa.fa-lg.fa-edit
          = link_to template_project_path(template_project), method: :delete, data: {confirm: 'are you sure?'} do
            %i.fa.fa-lg.fa-trash

.text-center
  = paginate @template_projects, theme: 'bootstrap'

app/views/template_projects/new.html.haml
- content_for :active, 'template_projects'

.page-header
  %h1 template project

%ol.breadcrumb
  %li= link_to 'template project', template_projects_path
  %li.active new

= render 'form'

app/views/template_projects/show.html.haml
- content_for :active, 'template_projects'

%ol.breadcrumb
  %li= link_to 'template project', template_projects_path
  %li.active= @template_project.title

#task-form
  %button.btn.btn-primary.mb10{'v-on' => 'click: close()'}
    %i.fa.fa-plus
  =render 'task_form'

%ul#task-list.list-group{data: {'project-id' => @template_project.id}}
  %li.list-group-item{'v-class' => "list-group-item-danger: task_type == 'release' && status != 'finished', list-group-item-success: status == 'finished'", 'v-repeat' => 'tasks'}
    %i.fa.fa-lg{'v-class' => 'fa-caret-right: !isEdit, fa-caret-down: isEdit', 'v-on' => 'click: edit(this)'}
    %i.fa.fa-star {{point}}
    %span {{passedTime}}
    %i.fa.fa-comment{'v-show' => "description != ''", 'v-on' => 'mouseenter: popover = true, mouseleave: popover = false'}
      .popover.bottom{'v-class' => 'static-popover: popover'}
        %h3.popover-title {{title}}
        .popover-content{'v-html' => 'description | indent'}
    %span {{title}}
    =render 'task_form'